plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  "tag:Name":
    - "enterprise-web-platform*"

hostnames:
  - tag:Name
  - instance-id

compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "'/home/lilia/.ssh/enterprise-key.pem'"
  ansible_python_interpreter: "'/usr/bin/python3'"

# hostnames:
#   - private-ip-address

# compose:
#   ansible_host: private_ip_address
